version: "3"

services:
  backend:
    image: arpit9667/pg-demo
    ports:
      - "5000:5000"
    depends_on: 
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: codegig
      POSTGRES_PASSWORD: postgres
      POSTGRE_USER: postgres
    ports:
      - "5432:5432"
